site_name: Transmogrifier
site_url: https://sapwoodstudio.github.io/transmogrifier
repo_url: https://github.com/sapwoodstudio/transmogrifier

nav:
  - Home: 'index.md'
  - Getting started:
    - Installation 📥: 'installation.md'
    - Quickstart Demo 🧪: 'quickstart_demo.md'
    # - User Interface 💻: 'user_interface.md'
    - General Usage 🏭: 'general_usage.md'
    - Update 🔁: 'update.md'
    - Uninstall 🔌: 'uninstall.md'
  - Features:
    - 'features_overview.md'
    - 'user_interface.md'
    - 'batch_convert.md'
    - 'apply_textures.md'
    - 'optimize_file_size.md'
    - 'mark_assets.md'
    - 'export_uv_maps.md'
    - 'set_scene_properties.md'
    - 'transform_objects.md'
    - 'run_custom_scripts.md'
    - 'log_conversions.md'
    # - 'convert_via_terminal.md'
  - FAQ: 'faq.md'
  - Community: 'community.md'
  - Changelog: 'changelog.md'

theme:
  name: material

  logo: assets/images/Transmogrifier_Logo_128.png

  favicon: assets/images/Transmogrifier_Logo_64.png

  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.path
    - navigation.indexes
    - navigation.footer
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: brown
      accent: light blue
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: brown
      accent: light blue

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
  - search
  - glightbox

markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - admonition
  - sane_lists
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      auto_title: false
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@sapwoodstudio

    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/sapwoodstudio

    - icon: fontawesome/brands/github
      link: https://github.com/SapwoodStudio

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 Sapwood Studio


docs_dir: src
edit_uri: edit/main/src/
site_dir: docs
